module.exports.places = [
  "Badminton Club",
  "Badminton Academy",
  "Badminton Center",
  "Badminton",
  "High School",
  "Gym",
  "Sports",
  "Sports Complex",
  "Facility",
  "Sports Facility",
  "Recreation Center",
  "University",
  "Community Center",
  "Badminton League",
];
